# Generated by Django 3.2.5 on 2022-02-11 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=1000)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(default=None)),
                ('sex', models.CharField(max_length=2)),
                ('birthday', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyWeb.blog')),
            ],
        ),
    ]
